baseURL = 'https://erengokirmak.com/'
locale = 'en-us'
title = '''Şükrü Eren Gökırmak'''
theme = 'PaperMod'
copyright = "şükrü eren gökırmak · [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)"
outputs = { home = ["HTML", "JSON", "RSS"] }

[taxonomies]
tag = "tags"
category = "categories"

[minify]
disableXML = true
minifyOutput = true

[params]
description = 'Personal blog of Şükrü Eren Gökırmak'
author = 'Şükrü Eren Gökırmak'
homeInfoParams = { title = 'welcome!', content = "I'm **Eren**, a **MSc in Computer Engineering** student at Bilkent University focusing on **Applied Cryptography**. I **write** and **code** and everything in-between. This is where to find them."}
ShowCodeCopyButtons = true
ShowBreadCrumbs = true
ShowRssButtonInSectionTermList = true
ShowFullTextinRSS = true
ShowReadingTime = true
assets.disableHLJS = true

[markup.highlight]
anchorLineNos = true
codeFences = true
style = "monokai"
wrapperClass = "highlight"
noClasses = true

[params.profileMode]
enabled = false
subtitle = "I write and code and everything in-between. this is where to find them."
[[params.profileMode.buttons]]
name = "Posts"
url = "/posts/"

[[params.socialIcons]]
name = 'GitHub'
url = 'https://github.com/erengokirmak'

[[params.socialIcons]]
name = 'LinkedIn'
url = 'https://linkedin.com/in/sukruerengokirmak'

[[params.socialIcons]]
name = 'ORCID'
url = 'https://orcid.org/0009-0003-2128-7872'

[[params.socialIcons]]
name = 'ResearchGate'
url = 'https://www.researchgate.net/profile/Suekrue-Goekirmak'

[[params.socialIcons]]
name = 'EMAIL'
url = 'mailto:sukruerengokirmak@gmail.com'

[[params.socialIcons]]
name = 'CV'
url = '/Sukru_Eren_Gokirmak_CV.pdf'

[[params.socialIcons]]
name = 'PGPKEY'
url = '/pub.asc'

[[params.socialIcons]]
name = 'RSS'
url = 'index.xml'

[[menu.main]]
name = 'Tags'
url = '/tags/'
weight = 20

[[menu.main]]
name = 'Archives'
url = '/archives/'
weight = 30

[[menu.main]]
name = 'Search'
url = '/search/'
weight = 40
